(function(){
 const style=document.createElement('style');
 style.textContent=`
 .global-search{position:relative;min-width:min(420px,42vw)}.global-search input{padding:10px 12px}.search-results{position:absolute;top:46px;left:0;right:0;z-index:80;background:#0e1b2c;border:1px solid #365071;border-radius:12px;max-height:360px;overflow:auto;box-shadow:0 12px 30px #0008}.search-result{padding:11px 12px;border-bottom:1px solid #23354e;cursor:pointer}.search-result:hover{background:#17253a}.search-result small{display:block;color:#9cabc0;margin-top:3px}
 .due-overdue{background:#3a1720!important;color:#ffc0c0!important}.due-soon{background:#3b3318!important;color:#ffe58b!important}.deposit-paid{background:#12382f!important;color:#83e7cc!important}.deposit-due{background:#3a1720!important;color:#ffc0c0!important}.deposit-partial{background:#3b3318!important;color:#ffe58b!important}
 .lineitems{margin-top:16px;border:1px solid #293c58;border-radius:12px;padding:14px;background:#0a1524}.lineitem-row{display:grid;grid-template-columns:2fr .55fr .85fr .85fr auto;gap:8px;align-items:center;margin-top:8px}.lineitem-total{font-weight:800;text-align:right}.archive-list{display:grid;gap:8px}.archive-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px;border:1px solid #293c58;border-radius:10px;background:#0a1524;flex-wrap:wrap}.audit-row{padding:10px 0;border-bottom:1px solid #23354e}.audit-row:last-child{border-bottom:0}.audit-row small{color:#9cabc0}.export-actions{display:flex;gap:8px;flex-wrap:wrap}.pro-section{margin-top:16px}
 @media(max-width:800px){.global-search{min-width:100%;order:3;width:100%}.lineitem-row{grid-template-columns:1fr 70px 90px}.lineitem-total{display:none}.lineitem-row button{grid-column:3}.topbar{flex-wrap:wrap}}
 `;document.head.appendChild(style);

 let customerArchives=[],auditLogs=[],archivedProjects=[],archivedRequests=[],archivedDocuments=[],docLineItems=[],lastCustomerKey=null;
 const norm=v=>String(v||'').trim().toLowerCase();
 const keyFor=x=>norm(x.email||x.customer_email)||norm(String(x.phone||x.customer_phone||x.whatsapp||'').replace(/\D/g,''))||norm(x.customer_name||x.business_name);
 async function logAudit(action,entityType,entityId,details={}){try{const u=await client.auth.getUser();await client.from('audit_logs').insert({business_id:profile.business_id,user_id:u.data.user?.id||null,action,entity_type:entityType||null,entity_id:entityId||null,details})}catch(e){}}
 function isArchivedCustomer(key){return customerArchives.some(x=>x.customer_key===key)}
 function daysUntil(date){if(!date)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(date+'T00:00:00');return Math.round((b-a)/86400000)}
 function duePill(date){const d=daysUntil(date);if(d===null)return '';if(d<0)return `<span class="pill due-overdue">${Math.abs(d)}d overdue</span>`;if(d===0)return '<span class="pill due-overdue">Due today</span>';if(d<=3)return `<span class="pill due-soon">Due in ${d}d</span>`;return `<span class="muted">${esc(date)}</span>`}
 function depositInfo(p){const agreed=Number(p.agreed_price||0),pct=Number(p.deposit_percent??50),req=agreed*pct/100,paid=paidForProject(p.id),rem=remainingForProject(p);if(agreed<=0)return {label:'No price',cls:'',required:req};if(rem<=0)return {label:'Paid in Full',cls:'deposit-paid',required:req};if(paid<=0)return {label:`Deposit Due ${money(req)}`,cls:'deposit-due',required:req};if(paid+0.001<req)return {label:`Deposit ${money(paid)}/${money(req)}`,cls:'deposit-partial',required:req};return {label:'Deposit Paid',cls:'deposit-paid',required:req}}

 requestTable=function(list){list=(list||[]).filter(x=>!x.archived_at);if(!list.length)return '<div class="empty">No requests found.</div>';return '<div class="tablewrap"><table><thead><tr><th>Customer</th><th>Service</th><th>Status</th><th>Follow-up</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow requestrow" data-id="${x.id}"><td><b>${esc(x.customer_name)}</b><br><span class="muted">${esc(x.email||x.phone||'')}</span></td><td>${esc(x.service||'—')}</td><td><span class="pill">${esc(pretty(x.status))}</span></td><td>${x.follow_up_date?duePill(x.follow_up_date):'—'}</td></tr>`).join('')+'</tbody></table></div>'}
 projectTable=function(list){list=(list||[]).filter(x=>!x.archived_at);if(!list.length)return '<div class="empty">No projects yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Project</th><th>Customer</th><th>Status</th><th>Deposit</th><th>Paid</th><th>Balance</th><th>Due</th></tr></thead><tbody>'+list.map(x=>{const dep=depositInfo(x);return `<tr class="clickrow projectrow" data-id="${x.id}"><td><b>${esc(x.project_name)}</b><br><span class="muted">${esc(x.service||'')}</span></td><td>${esc(x.customer_name)}</td><td><span class="pill">${esc(pretty(x.status))}</span></td><td><span class="pill ${dep.cls}">${esc(dep.label)}</span></td><td class="good">${money(paidForProject(x.id))}</td><td>${money(remainingForProject(x))}</td><td>${x.due_date?duePill(x.due_date):'—'}</td></tr>`}).join('')+'</tbody></table></div>'}
 documentTable=function(list){list=(list||[]).filter(x=>!x.archived_at);if(!list.length)return '<div class="empty">No documents yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Type</th><th>Number</th><th>Client</th><th>Status</th><th>Amount</th><th>Due</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow documentrow" data-id="${x.id}"><td><b>${esc(pretty(x.document_type))}</b></td><td>${esc(x.document_number||'—')}</td><td>${esc(x.customer_name||'—')}</td><td><span class="pill docstatus">${esc(pretty(x.status))}</span></td><td>${money(x.amount)}</td><td>${x.document_type==='invoice'&&x.status!=='paid'&&x.due_date?duePill(x.due_date):(x.due_date?esc(x.due_date):'—')}</td></tr>`).join('')+'</tbody></table></div>'}

 function ensureSearch(){const top=document.querySelector('.main > .topbar');if(!top||$('globalSearch'))return;const box=document.createElement('div');box.className='global-search';box.innerHTML='<input id="globalSearch" placeholder="Search customers, phone, projects, invoices..."><div id="globalSearchResults" class="search-results hidden"></div>';top.insertBefore(box,top.querySelector('.actions'));$('globalSearch').oninput=renderSearch;$('globalSearch').onfocus=renderSearch;document.addEventListener('click',e=>{if(!box.contains(e.target))show('globalSearchResults',false)})}
 function renderSearch(){const q=norm($('globalSearch').value);const out=$('globalSearchResults');if(q.length<2){show('globalSearchResults',false);return}const items=[];requests.forEach(r=>{if([r.customer_name,r.phone,r.whatsapp,r.email,r.service].some(v=>norm(v).includes(q)))items.push({type:'request',id:r.id,title:r.customer_name||'Request',sub:'Request · '+(r.service||pretty(r.status))})});projects.forEach(p=>{if([p.project_name,p.customer_name,p.phone,p.email,p.service].some(v=>norm(v).includes(q)))items.push({type:'project',id:p.id,title:p.project_name,sub:'Project · '+p.customer_name})});documents.forEach(d=>{if([d.document_number,d.customer_name,d.customer_phone,d.customer_email,d.title,d.service].some(v=>norm(v).includes(q)))items.push({type:'document',id:d.id,title:d.document_number||pretty(d.document_type),sub:pretty(d.document_type)+' · '+(d.customer_name||'')})});const customers=new Map();[...requests,...projects].forEach(x=>{const k=keyFor(x);if(k&&!customers.has(k))customers.set(k,{key:k,name:x.customer_name||'Customer',phone:x.phone||x.whatsapp||'',email:x.email||''})});customers.forEach(c=>{if([c.name,c.phone,c.email].some(v=>norm(v).includes(q)))items.unshift({type:'customer',id:c.key,title:c.name,sub:'Customer · '+(c.phone||c.email||'')})});out.innerHTML=items.slice(0,12).map((x,i)=>`<div class="search-result" data-sidx="${i}"><b>${esc(x.title)}</b><small>${esc(x.sub)}</small></div>`).join('')||'<div class="search-result muted">No results</div>';show('globalSearchResults',true);document.querySelectorAll('[data-sidx]').forEach(el=>el.onclick=()=>{const x=items[Number(el.dataset.sidx)];show('globalSearchResults',false);$('globalSearch').value='';if(x.type==='project')openProject(x.id);else if(x.type==='request')openDetail(x.id);else if(x.type==='document')openDocument(x.id);else{setPage('customers');setTimeout(()=>document.querySelector(`.customerrow[data-key="${CSS.escape(x.id)}"]`)?.click(),50)}})}

 function ensureProjectTools(){const box=$('projectModal')?.querySelector('.modalbox');if(!box)return;if(!$('pDepositPercent')){const extra=$('projectExtraGrid')||box.querySelector(':scope > .grid2');const div=document.createElement('div');div.innerHTML='<label>Deposit %</label><input id="pDepositPercent" type="number" min="0" max="100" step="1" value="50">';extra?.appendChild(div);const dep=document.createElement('div');dep.id='projectDepositStatus';dep.className='notice';dep.style.marginTop='12px';($('paymentBox')||box.querySelector('.toolbar'))?.before(dep)}if(!$('archiveProjectBtn')){const b=document.createElement('button');b.id='archiveProjectBtn';b.className='secondary';b.textContent='Archive Project';$('deleteProject')?.before(b);b.onclick=archiveProject}}
 function updateDepositStatus(){if(!selectedProject||!$('projectDepositStatus'))return;const dep=depositInfo(selectedProject);$('projectDepositStatus').innerHTML=`<b>Deposit:</b> ${esc(dep.label)} <span class="muted">(${Number(selectedProject.deposit_percent??50)}% required)</span>`}
 const oldUpdatePaymentSummary=updatePaymentSummary;updatePaymentSummary=function(){oldUpdatePaymentSummary();updateDepositStatus()}
 const oldOpenProject2=openProject;openProject=function(id){oldOpenProject2(id);ensureProjectTools();if(selectedProject){$('pDepositPercent').value=selectedProject.deposit_percent??50;show('archiveProjectBtn',true);updateDepositStatus()}}
 const oldBlankProject2=blankProject;blankProject=function(){oldBlankProject2();ensureProjectTools();$('pDepositPercent').value=50;show('archiveProjectBtn',false);if($('projectDepositStatus'))$('projectDepositStatus').textContent='Deposit tracking starts after the project is saved.'}
 const oldProjectFromRequest2=projectFromRequest;projectFromRequest=function(){oldProjectFromRequest2();ensureProjectTools();$('pDepositPercent').value=50;show('archiveProjectBtn',false)}
 $('newProjectBtn').onclick=blankProject;$('createProjectBtn').onclick=projectFromRequest;
 async function saveProjectPro(){const isNew=!selectedProject,payload={business_id:profile.business_id,request_id:projectRequestId,project_name:$('pName').value.trim(),customer_name:$('pCustomer').value.trim(),phone:$('pPhone').value.trim()||null,email:$('pEmail').value.trim()||null,service:$('pService').value.trim()||null,status:$('pStatus').value,agreed_price:$('pPrice').value?Number($('pPrice').value):null,start_date:$('pStart').value||null,due_date:$('pDue').value||null,notes:$('pNotes').value.trim()||null,deposit_percent:Number($('pDepositPercent')?.value||50)};if(!payload.project_name||!payload.customer_name)return;let q;if(selectedProject)q=await client.from('projects').update(payload).eq('id',selectedProject.id).eq('business_id',profile.business_id).select().single();else q=await client.from('projects').insert(payload).select().single();if(q.error){$('projectMsg').className='msg err';$('projectMsg').textContent=q.error.message;return}if(projectRequestId&&isNew)await client.from('requests').update({status:'in_progress'}).eq('id',projectRequestId).eq('business_id',profile.business_id);await logAudit(isNew?'project_created':'project_updated','project',q.data.id,{name:q.data.project_name,status:q.data.status});show('projectModal',false);await refresh();setPage('projects')}
 $('saveProject').onclick=saveProjectPro;
 async function archiveProject(){if(!selectedProject||!confirm('Archive this project? Nothing will be deleted.'))return;await client.from('projects').update({archived_at:new Date().toISOString()}).eq('id',selectedProject.id).eq('business_id',profile.business_id);await logAudit('project_archived','project',selectedProject.id,{name:selectedProject.project_name});show('projectModal',false);await refresh();setPage('projects')}

 function ensureArchiveButtons(){if(!$('archiveRequestBtn')){const b=document.createElement('button');b.id='archiveRequestBtn';b.className='secondary';b.textContent='Archive Request';$('saveDetail')?.after(b);b.onclick=async()=>{if(!selected||!confirm('Archive this request?'))return;await client.from('requests').update({archived_at:new Date().toISOString()}).eq('id',selected.id).eq('business_id',profile.business_id);await logAudit('request_archived','request',selected.id,{customer:selected.customer_name});show('detailModal',false);await refresh()}}if(!$('archiveDocumentBtn')){const b=document.createElement('button');b.id='archiveDocumentBtn';b.className='secondary';b.textContent='Archive';$('deleteDocument')?.before(b);b.onclick=async()=>{if(!selectedDocument?.id||!confirm('Archive this document?'))return;await client.from('documents').update({archived_at:new Date().toISOString()}).eq('id',selectedDocument.id).eq('business_id',profile.business_id);await logAudit('document_archived','document',selectedDocument.id,{number:selectedDocument.document_number});show('documentModal',false);await refresh();setPage('documents')}}}
 const oldOpenDetail=openDetail;openDetail=function(id){oldOpenDetail(id);ensureArchiveButtons();show('archiveRequestBtn',true)};

 function ensureLineItems(){const modal=$('documentModal')?.querySelector('.modalbox');if(!modal||$('docLineItemsBox'))return;const sec=document.createElement('div');sec.id='docLineItemsBox';sec.className='lineitems';sec.innerHTML='<div class="pageintro"><div><h3 style="margin:0">Invoice items</h3><div class="simple-hint">Customer-visible charges only. Your private expenses stay hidden.</div></div><button id="addLineItem" class="secondary">+ Add Item</button></div><div id="docLineItems"></div><div style="text-align:right;margin-top:10px"><b>Total: <span id="lineItemsTotal">$0</span></b></div>';const title=$('docTitle');title?.before(sec);$('addLineItem').onclick=()=>{docLineItems.push({description:'',qty:1,unit_price:0});renderLineItems()}}
 function lineTotal(){return docLineItems.reduce((a,x)=>a+Number(x.qty||0)*Number(x.unit_price||0),0)}
 function renderLineItems(){ensureLineItems();const box=$('docLineItemsBox');if(!box)return;show('docLineItemsBox',$('docType').value!=='agreement');$('docLineItems').innerHTML=docLineItems.map((x,i)=>`<div class="lineitem-row" data-li="${i}"><input data-f="description" value="${esc(x.description||'')}" placeholder="Website, SEO, language add-on..."><input data-f="qty" type="number" min="0" step="1" value="${Number(x.qty||1)}"><input data-f="unit_price" type="number" min="0" step="0.01" value="${Number(x.unit_price||0)}"><div class="lineitem-total">${money(Number(x.qty||0)*Number(x.unit_price||0))}</div><button class="danger liRemove">✕</button></div>`).join('')||'<div class="muted">No items yet. Add an item or keep the single total amount.</div>';$('lineItemsTotal').textContent=money(lineTotal());document.querySelectorAll('[data-li]').forEach(row=>{const i=Number(row.dataset.li);row.querySelectorAll('input').forEach(inp=>inp.oninput=()=>{docLineItems[i][inp.dataset.f]=inp.dataset.f==='description'?inp.value:Number(inp.value||0);$('docAmount').value=lineTotal();renderLineItems()});row.querySelector('.liRemove').onclick=()=>{docLineItems.splice(i,1);$('docAmount').value=lineTotal();renderLineItems()}});if(docLineItems.length)$('docAmount').value=lineTotal()}
 const oldFillDocument=fillDocument;fillDocument=function(d){oldFillDocument(d);ensureArchiveButtons();ensureLineItems();docLineItems=Array.isArray(d.line_items)?d.line_items.map(x=>({...x})):[];if(!docLineItems.length&&d.document_type==='invoice'&&Number(d.amount||0)>0)docLineItems=[{description:d.service||d.title||'Service',qty:1,unit_price:Number(d.amount||0)}];renderLineItems();show('archiveDocumentBtn',!!d.id)};
 $('docType').addEventListener('change',renderLineItems);
 async function saveDocumentPro(){const project=projects.find(p=>p.id===$('docProject').value),itemAmount=docLineItems.length?lineTotal():Number($('docAmount').value||0),paid=$('docType').value==='receipt'?Number($('docPaid').value||0):(project?paidForProject(project.id):Number($('docPaid').value||0)),balance=Math.max(0,itemAmount-paid);let status=$('docStatus').value;if($('docType').value==='invoice')status=balance<=0?'paid':(status==='draft'?'unpaid':status);if($('docType').value==='receipt')status='paid';const payload={business_id:profile.business_id,project_id:$('docProject').value||null,document_type:$('docType').value,status,document_number:$('docNumber').value.trim()||null,customer_name:$('docClient').value.trim()||null,business_name:$('docBusiness').value.trim()||null,customer_email:$('docEmail').value.trim()||null,customer_phone:$('docPhone').value.trim()||null,title:$('docTitle').value.trim()||null,description:$('docDescription').value.trim()||null,service:$('docService').value.trim()||null,amount:itemAmount,issue_date:$('docIssue').value||new Date().toISOString().slice(0,10),due_date:$('docDue').value||null,start_date:$('docStart').value||null,delivery_date:$('docDelivery').value||null,deposit_percent:Number($('docDeposit').value||50),amount_paid:paid,balance,payment_methods:['OMT','WHISH MONEY','Personally'],terms:$('docTerms').value.trim()||null,notes:$('docNotes').value.trim()||null,line_items:docLineItems};let q;if(selectedDocument?.id)q=await client.from('documents').update(payload).eq('id',selectedDocument.id).eq('business_id',profile.business_id).select().single();else q=await client.from('documents').insert(payload).select().single();if(q.error){$('documentMsg').className='msg err';$('documentMsg').textContent=q.error.message;return}await logAudit(selectedDocument?.id?'document_updated':'document_created','document',q.data.id,{number:q.data.document_number,type:q.data.document_type,amount:q.data.amount});selectedDocument=q.data;$('documentMsg').className='msg ok';$('documentMsg').textContent='Saved. You can now preview or send it.';await refresh();selectedDocument=documents.find(d=>d.id===q.data.id)||q.data;fillDocument({...selectedDocument})}
 saveDocument=saveDocumentPro;$('saveDocument').onclick=saveDocumentPro;

 const baseAddPayment=$('addPayment').onclick;$('addPayment').onclick=async function(){const pid=selectedProject?.id,before=pid?paidForProject(pid):0;await baseAddPayment.call(this);if(pid&&paidForProject(pid)>before)await logAudit('payment_added','project',pid,{amount:paidForProject(pid)-before})};
 const baseComplete=$('completePaid').onclick;$('completePaid').onclick=async function(){const pid=selectedProject?.id;await baseComplete.call(this);if(pid)await logAudit('project_completed','project',pid,{})};
 const baseUpdateSelected=updateSelected;updateSelected=async function(patch){const id=selected?.id;await baseUpdateSelected(patch);if(id)await logAudit('request_updated','request',id,patch)};

 function csvCell(v){const s=typeof v==='object'?JSON.stringify(v):String(v??'');return '"'+s.replaceAll('"','""')+'"'}
 function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
 function exportCsv(name,rows){if(!rows.length){alert('No data to export.');return}const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))],csv=[keys.map(csvCell).join(','),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\n');download(name,csv)}
 function customerExport(){const m=new Map();[...requests,...projects].forEach(x=>{const k=keyFor(x);if(!k)return;const c=m.get(k)||{name:x.customer_name||'',phone:x.phone||x.whatsapp||'',email:x.email||'',projects:0,paid:0,balance:0};if(x.project_name){c.projects++;c.paid+=paidForProject(x.id);c.balance+=remainingForProject(x)}m.set(k,c)});return [...m.values()]}
 function ensureBusinessTools(){const settings=$('page-settings')?.querySelector('.section');if(!settings)return;if(!$('exportTools')){const sec=document.createElement('div');sec.id='exportTools';sec.className='section pro-section';sec.innerHTML='<h2>Export & Backup</h2><p class="muted">Download business records anytime.</p><div class="export-actions"><button data-export="customers">Customers CSV</button><button data-export="projects">Projects CSV</button><button data-export="payments">Payments CSV</button><button data-export="expenses">Expenses CSV</button><button id="jsonBackup" class="secondary">Full JSON Backup</button></div>';settings.after(sec);document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{const t=b.dataset.export;if(t==='customers')exportCsv('kelvodigital-customers.csv',customerExport());if(t==='projects')exportCsv('kelvodigital-projects.csv',projects);if(t==='payments')exportCsv('kelvodigital-payments.csv',payments);if(t==='expenses')exportCsv('kelvodigital-expenses.csv',expenses)});$('jsonBackup').onclick=()=>{download('kelvodigital-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({exported_at:new Date().toISOString(),requests,projects,payments,documents,expenses},null,2),'application/json');logAudit('business_exported','business',null,{})}}
  if(!$('archiveTools')){const sec=document.createElement('div');sec.id='archiveTools';sec.className='section pro-section';sec.innerHTML='<h2>Archive</h2><p class="muted">Archived records are hidden from normal work but never deleted.</p><div id="archiveRows" class="archive-list"></div>';document.querySelector('.main #exportTools')?.after(sec)}
  if(!$('auditTools')){const sec=document.createElement('div');sec.id='auditTools';sec.className='section pro-section';sec.innerHTML='<h2>Recent Activity</h2><div id="auditRows"></div>';document.querySelector('.main #archiveTools')?.after(sec)}renderArchiveAndAudit()}
 function renderArchiveAndAudit(){if($('archiveRows')){const rows=[...archivedRequests.map(x=>({type:'request',id:x.id,label:'Request · '+(x.customer_name||x.service||'')})),...archivedProjects.map(x=>({type:'project',id:x.id,label:'Project · '+x.project_name})),...archivedDocuments.map(x=>({type:'document',id:x.id,label:pretty(x.document_type)+' · '+(x.document_number||x.customer_name||'')})),...customerArchives.map(x=>({type:'customer',id:x.id,key:x.customer_key,label:'Customer · '+(x.customer_name||x.customer_key)}))];$('archiveRows').innerHTML=rows.length?rows.map((x,i)=>`<div class="archive-row" data-ar="${i}"><span>${esc(x.label)}</span><button class="secondary">Restore</button></div>`).join(''):'<div class="muted">Nothing archived.</div>';document.querySelectorAll('[data-ar]').forEach(el=>el.querySelector('button').onclick=()=>restoreArchive(rows[Number(el.dataset.ar)]))}if($('auditRows'))$('auditRows').innerHTML=auditLogs.length?auditLogs.slice(0,25).map(x=>`<div class="audit-row"><b>${esc(pretty(x.action))}</b><br><small>${new Date(x.created_at).toLocaleString()}${x.details?.name?' · '+esc(x.details.name):''}${x.details?.number?' · '+esc(x.details.number):''}</small></div>`).join(''):'<div class="muted">No activity yet.</div>'}
 async function restoreArchive(x){if(x.type==='customer')await client.from('customer_archives').delete().eq('id',x.id).eq('business_id',profile.business_id);else await client.from(x.type==='request'?'requests':x.type==='project'?'projects':'documents').update({archived_at:null}).eq('id',x.id).eq('business_id',profile.business_id);await logAudit(x.type+'_restored',x.type,x.type==='customer'?null:x.id,{});await refresh()}

 const oldRenderCustomers=renderCustomers;renderCustomers=function(){oldRenderCustomers();const rows=[...document.querySelectorAll('.customerrow')];rows.forEach(row=>{const key=row.dataset.key;if(isArchivedCustomer(key))row.remove();else{row.addEventListener('click',()=>{lastCustomerKey=key;setTimeout(ensureCustomerArchiveButton,0)})}});const tbody=$('customerRows')?.querySelector('tbody');if(tbody&&!tbody.children.length)$('customerRows').innerHTML='<div class="empty">No active customers.</div>'}
 function ensureCustomerArchiveButton(){const modal=$('customerModal');if(!modal||!lastCustomerKey)return;if(!$('archiveCustomerBtn')){const b=document.createElement('button');b.id='archiveCustomerBtn';b.className='secondary';b.textContent='Archive Customer';modal.querySelector('.customer-actions')?.appendChild(b)}$('archiveCustomerBtn').onclick=async()=>{if(!confirm('Archive this customer? Their records will stay safe.'))return;const name=$('cName')?.textContent||null;const q=await client.from('customer_archives').upsert({business_id:profile.business_id,customer_key:lastCustomerKey,customer_name:name},{onConflict:'business_id,customer_key'});if(q.error){alert(q.error.message);return}await logAudit('customer_archived','customer',null,{name});show('customerModal',false);await refresh();setPage('customers')}}

 const oldRefreshPro=refresh;refresh=async function(){await oldRefreshPro();if(!profile)return;archivedRequests=requests.filter(x=>x.archived_at);archivedProjects=projects.filter(x=>x.archived_at);archivedDocuments=documents.filter(x=>x.archived_at);requests=requests.filter(x=>!x.archived_at);projects=projects.filter(x=>!x.archived_at);documents=documents.filter(x=>!x.archived_at);const [ca,al]=await Promise.all([client.from('customer_archives').select('*').eq('business_id',profile.business_id),client.from('audit_logs').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false}).limit(50)]);customerArchives=ca.data||[];auditLogs=al.data||[];render();ensureSearch();ensureBusinessTools();renderArchiveAndAudit()};$('refreshBtn').onclick=refresh;
 const oldSetPage=setPage;setPage=function(name){oldSetPage(name);ensureSearch();if(name==='settings')ensureBusinessTools()};
 ensureSearch();ensureProjectTools();ensureArchiveButtons();ensureLineItems();ensureBusinessTools();if(profile)refresh();
})();