const modernManagerStyle=document.createElement('style');
modernManagerStyle.textContent=`
:root{--bg:#070b14;--panel:#0f1726;--panel2:#0b1220;--line:#1f2b3d;--text:#f5f7fb;--muted:#8fa0b8;--blue:#5b7cff;--ok:#38d3b1;--danger:#ff6f7d;--amber:#f6b75d;--cyan:#25c8e8;--purple:#9b7cff}
body{background:radial-gradient(circle at 78% -10%,rgba(91,124,255,.12),transparent 34%),radial-gradient(circle at 16% 110%,rgba(37,200,232,.08),transparent 30%),var(--bg);letter-spacing:.005em}
.app{grid-template-columns:230px minmax(0,1fr)}
.sidebar{background:linear-gradient(180deg,rgba(14,22,36,.98),rgba(8,14,25,.98));border-right:1px solid rgba(255,255,255,.06);padding:22px 14px;box-shadow:12px 0 35px rgba(0,0,0,.14)}
.brand{padding:0 8px 24px;font-size:18px;letter-spacing:-.02em}.brand img{width:42px;height:32px;border-radius:9px;box-shadow:0 6px 16px rgba(0,0,0,.18)}
.navwrap{display:flex;flex-direction:column;gap:4px}.navbtn{position:relative;margin:0;padding:11px 13px;border-radius:11px;color:#9eabc0;font-weight:700;transition:.18s ease}.navbtn:hover{background:rgba(255,255,255,.045);color:#fff;transform:translateX(2px)}.navbtn.active{background:linear-gradient(90deg,rgba(91,124,255,.22),rgba(91,124,255,.08));color:#fff;box-shadow:inset 3px 0 0 #6f8cff}.navbtn.active:after{content:'';position:absolute;right:10px;top:50%;width:6px;height:6px;border-radius:50%;background:#75a7ff;transform:translateY(-50%);box-shadow:0 0 14px rgba(117,167,255,.8)}
.sidebottom{bottom:20px}.sidebottom .ghost{background:rgba(255,255,255,.025)!important}
.main{padding:32px clamp(22px,3vw,42px);max-width:1600px;width:100%;margin:0 auto}.topbar{margin-bottom:26px}.topbar h1{font-size:30px;letter-spacing:-.035em}.topbar .muted{margin-top:4px;font-size:13px}
.btn,button{border-radius:11px;padding:10px 14px;font-weight:750;box-shadow:none;transition:transform .16s ease,box-shadow .16s ease,background .16s ease}.btn:hover,button:hover{transform:translateY(-1px)}button:not(.navbtn):not(.filter),.btn:not(.ghost){box-shadow:0 7px 18px rgba(40,68,170,.16)}.secondary{background:#182437!important}.danger{background:#5f2632!important}.success{background:#106c59!important}.ghost{border-color:#2a3850!important}
.notice{border:1px solid rgba(91,124,255,.22);border-left:3px solid #6b88ff;border-radius:14px;background:linear-gradient(90deg,rgba(91,124,255,.09),rgba(91,124,255,.025));padding:14px 16px;color:#c9d4e5}
.cards{grid-template-columns:repeat(6,minmax(145px,1fr));gap:12px;margin:18px 0 26px}.card{position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.065);border-radius:15px;padding:17px 16px;background:linear-gradient(180deg,rgba(18,28,45,.96),rgba(13,21,34,.96));box-shadow:0 12px 26px rgba(0,0,0,.11)}.card:before{content:'';position:absolute;left:0;right:0;top:0;height:3px;background:#5b7cff}.card:nth-child(1):before{background:var(--amber)}.card:nth-child(2):before{background:var(--blue)}.card:nth-child(3):before{background:var(--ok)}.card:nth-child(4):before{background:var(--danger)}.card:nth-child(5):before{background:var(--cyan)}.card:nth-child(6):before{background:var(--purple)}.card .muted{font-size:12px;text-transform:uppercase;letter-spacing:.07em;font-weight:800}.num{font-size:27px;letter-spacing:-.045em;margin-top:7px}
.section{margin-top:18px;background:rgba(13,21,34,.72);border:1px solid rgba(255,255,255,.06);border-radius:17px;padding:20px 20px 22px;box-shadow:0 12px 30px rgba(0,0,0,.08)}.section h2{font-size:18px;letter-spacing:-.02em;margin-bottom:6px}.section .topbar{margin-bottom:12px}.section>p.muted,.topbar p.muted{margin-top:5px}
.toolbar{gap:7px;margin:16px 0}.filter{background:#111c2d;color:#93a2b7;border:1px solid rgba(255,255,255,.055);padding:8px 12px;border-radius:999px;font-size:13px;box-shadow:none}.filter:hover{background:#18263a;color:#e8eef8}.filter.active{background:linear-gradient(135deg,#5b7cff,#4869e6);color:white;border-color:transparent;box-shadow:0 5px 14px rgba(91,124,255,.2)}
.tablewrap{border:1px solid rgba(255,255,255,.06);border-radius:14px;background:#0b1321;box-shadow:inset 0 1px 0 rgba(255,255,255,.025)}table{background:transparent}th{background:#0e1828;color:#7689a4;font-size:10.5px;letter-spacing:.09em;padding:11px 14px}td{padding:14px;border-bottom:1px solid rgba(255,255,255,.045)}tbody tr:last-child td{border-bottom:0}.clickrow{transition:background .15s ease}.clickrow:hover{background:rgba(91,124,255,.075)}.pill{background:rgba(91,124,255,.12);border:1px solid rgba(91,124,255,.18);color:#aebdff;padding:5px 9px;font-size:11px}
.statsline{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.statmini{min-width:0;background:linear-gradient(180deg,#101b2c,#0b1422);border:1px solid rgba(255,255,255,.06);border-radius:14px;padding:14px 15px}.statmini b{font-size:12px;color:#8fa0b8}.statmini .num{font-size:24px}
input,textarea,select{background:#0a1220;border:1px solid #26364c;border-radius:11px;padding:11px 12px;transition:border-color .15s ease,box-shadow .15s ease}input:focus,textarea:focus,select:focus{outline:0;border-color:#5b7cff;box-shadow:0 0 0 3px rgba(91,124,255,.13)}label{font-size:12px;color:#9aa9bd;letter-spacing:.02em}
.modal{background:rgba(2,6,12,.72);backdrop-filter:blur(8px)}.modalbox{background:linear-gradient(180deg,#101a2a,#0a1220);border:1px solid rgba(255,255,255,.09);border-radius:20px;padding:24px;box-shadow:0 24px 80px rgba(0,0,0,.42)}.modalhead{padding-bottom:14px;border-bottom:1px solid rgba(255,255,255,.055)}.close{border-radius:10px!important}.detailitem,.paybox,.docbox,.paymetric{background:#0b1422;border-color:rgba(255,255,255,.06);border-radius:13px}.detailitem b,.paymetric b{color:#8092ab}.empty{border:1px dashed rgba(255,255,255,.08);border-radius:13px;background:rgba(255,255,255,.015);padding:36px}
.authwrap{max-width:460px;margin:8vh auto}.authwrap .panel{background:linear-gradient(180deg,#111c2d,#0b1422);border:1px solid rgba(255,255,255,.08);box-shadow:0 22px 70px rgba(0,0,0,.28);border-radius:22px}
@media(max-width:1200px){.cards{grid-template-columns:repeat(3,1fr)}}
@media(max-width:900px){.app{grid-template-columns:1fr}.sidebar{height:auto;position:static;padding:14px;border-right:0;border-bottom:1px solid rgba(255,255,255,.06)}.brand{padding-bottom:12px}.navwrap{display:flex;flex-direction:row;gap:5px;overflow:auto;padding-bottom:5px}.navbtn{white-space:nowrap;width:auto}.sidebottom{position:static;margin-top:10px}.main{padding:22px 16px}.cards{grid-template-columns:repeat(2,1fr)}.section{padding:16px}.topbar h1{font-size:26px}}
@media(max-width:520px){.cards{grid-template-columns:1fr 1fr;gap:9px}.card{padding:14px}.num{font-size:23px}.topbar{align-items:flex-start}.topbar .actions{margin-left:auto}.section{border-radius:14px}.modalbox{padding:17px;border-radius:16px}}
`;
document.head.appendChild(modernManagerStyle);

const SUPABASE_URL="https://fbgphoixzpykcpdbfbhd.supabase.co",SUPABASE_KEY="sb_publishable_U9E9amYU8RvRz4J1etv7Sw_svCjP-U-";
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on);
let profile=null,requests=[],projects=[],payments=[],documents=[],filter='all',pfilter='all',dfilter='all',selected=null,selectedProject=null,selectedDocument=null,projectRequestId=null;
const defaultAgreementTerms=`1. Scope of Work: KelvoDigital will provide the selected service described in this agreement, offer sheet or invoice.
2. Delivery: Standard target is about 3 weeks after the required content and deposit are received.
3. Revisions: Up to 2 rounds of revisions are included unless otherwise agreed.
4. Payment: A 50% deposit is required to begin. The remaining balance is due before launch or handover.
5. Client Responsibilities: Client provides logo, photos, text, prices and required business information, reviews drafts and gives timely feedback.
6. Domain: After the first year, domain renewal is paid by the client.
7. Search/SEO: Search ranking or customer numbers cannot be guaranteed.
8. Approval: By accepting/signing, both parties confirm they understand and accept these terms.`;
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}
function pretty(s){return String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function phoneDigits(v){return String(v||'').replace(/\D/g,'')}
function paidForProject(id){return payments.filter(p=>p.project_id===id).reduce((a,p)=>a+Number(p.amount||0),0)}
function remainingForProject(p){return Math.max(0,Number(p.agreed_price||0)-paidForProject(p.id))}
function shareUrl(d){return location.origin+location.pathname.replace(/manager\.html.*$/,'document.html')+'?token='+encodeURIComponent(d.share_token)}
function setPage(name){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('page-'+name).classList.remove('hidden');document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('pageTitle').textContent=({dashboard:'Dashboard',requests:'Requests',add:'Add Request',projects:'Projects',documents:'Documents',customers:'Customers',income:'Income',settings:'Settings'})[name]||'Business Manager';render()}
function requestTable(list){if(!list.length)return '<div class="empty">No requests found.</div>';return '<div class="tablewrap"><table><thead><tr><th>Customer</th><th>Type</th><th>Service</th><th>Status</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow requestrow" data-id="${x.id}"><td><b>${esc(x.customer_name)}</b><br><span class="muted">${esc(x.email||x.phone||'')}</span></td><td>${esc(x.request_type)}</td><td>${esc(x.service||'—')}</td><td><span class="pill">${esc(pretty(x.status))}</span></td></tr>`).join('')+'</tbody></table></div>'}
function projectTable(list){if(!list.length)return '<div class="empty">No projects yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Project</th><th>Customer</th><th>Status</th><th>Agreed</th><th>Paid</th><th>Balance</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow projectrow" data-id="${x.id}"><td><b>${esc(x.project_name)}</b><br><span class="muted">${esc(x.service||'')}</span></td><td>${esc(x.customer_name)}</td><td><span class="pill">${esc(pretty(x.status))}</span></td><td>${money(x.agreed_price)}</td><td class="good">${money(paidForProject(x.id))}</td><td>${money(remainingForProject(x))}</td></tr>`).join('')+'</tbody></table></div>'}
function documentTable(list){if(!list.length)return '<div class="empty">No documents yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Type</th><th>Number</th><th>Client</th><th>Service</th><th>Status</th><th>Amount</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow documentrow" data-id="${x.id}"><td><b>${esc(pretty(x.document_type))}</b></td><td>${esc(x.document_number||'—')}</td><td>${esc(x.customer_name||'—')}</td><td>${esc(x.service||x.title||'—')}</td><td><span class="pill docstatus">${esc(pretty(x.status))}</span></td><td>${money(x.amount)}</td></tr>`).join('')+'</tbody></table></div>'}
function paymentTable(){if(!payments.length)return '<div class="empty">No payments recorded yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Date</th><th>Project</th><th>Amount</th><th>Method</th><th>Note</th></tr></thead><tbody>'+payments.map(p=>{const pr=projects.find(x=>x.id===p.project_id);return `<tr><td>${esc(p.payment_date||'—')}</td><td>${esc(pr?.project_name||'Project')}</td><td class="good"><b>${money(p.amount)}</b></td><td>${esc(p.payment_method||'—')}</td><td>${esc(p.notes||'—')}</td></tr>`}).join('')+'</tbody></table></div>'}
function renderCustomers(){const map=new Map();requests.forEach(x=>{const key=(x.email||x.phone||x.customer_name||'').toLowerCase();if(!map.has(key))map.set(key,x)});const list=[...map.values()];$('customersList').innerHTML=list.length?'<div class="tablewrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Last service</th></tr></thead><tbody>'+list.map(x=>`<tr><td>${esc(x.customer_name)}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.email||'—')}</td><td>${esc(x.service||'—')}</td></tr>`).join('')+'</tbody></table></div>':'<div class="empty">No customers yet.</div>'}
function renderIncome(){const paid=payments.reduce((a,p)=>a+Number(p.amount||0),0),value=projects.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+Number(x.agreed_price||0),0),out=projects.filter(x=>x.status!=='cancelled').reduce((a,p)=>a+remainingForProject(p),0);$('incomeTotal').textContent=money(paid);$('outstandingTotal').textContent=money(out);$('projectValue').textContent=money(value);$('paymentsTable').innerHTML=paymentTable()}
function render(){if(!profile)return;const pending=requests.filter(x=>x.status==='pending').length,active=projects.filter(x=>!['completed','cancelled'].includes(x.status)).length,paid=payments.reduce((a,p)=>a+Number(p.amount||0),0),out=projects.filter(x=>x.status!=='cancelled').reduce((a,p)=>a+remainingForProject(p),0);$('pending').textContent=pending;$('activeProjects').textContent=active;$('income').textContent=money(paid);$('outstanding').textContent=money(out);$('dashboardProjects').innerHTML=projectTable(projects.filter(x=>!['completed','cancelled'].includes(x.status)).slice(0,6));$('dashboardDocuments').innerHTML=documentTable(documents.slice(0,6));let rl=requests;if(filter==='quote'||filter==='booking')rl=requests.filter(x=>x.request_type===filter);else if(filter!=='all')rl=requests.filter(x=>x.status===filter);$('requestsTable').innerHTML=requestTable(rl);let pl=pfilter==='all'?projects:projects.filter(x=>x.status===pfilter);$('projectsTable').innerHTML=projectTable(pl);let dl=dfilter==='all'?documents:documents.filter(x=>x.document_type===dfilter);$('documentsTable').innerHTML=documentTable(dl);bindRows();renderCustomers();renderIncome()}
function bindRows(){document.querySelectorAll('.requestrow').forEach(r=>r.onclick=()=>openDetail(r.dataset.id));document.querySelectorAll('.projectrow').forEach(r=>r.onclick=()=>openProject(r.dataset.id));document.querySelectorAll('.documentrow').forEach(r=>r.onclick=()=>openDocument(r.dataset.id))}
async function refresh(){const [rq,pq,pyq,dq]=await Promise.all([client.from('requests').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false}),client.from('projects').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false}),client.from('payments').select('*').eq('business_id',profile.business_id).order('payment_date',{ascending:false}).order('created_at',{ascending:false}),client.from('documents').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false})]);for(const q of [rq,pq,pyq,dq])if(q.error){$('globalMsg').className='msg err';$('globalMsg').textContent=q.error.message;return}requests=rq.data||[];projects=pq.data||[];payments=pyq.data||[];documents=dq.data||[];$('globalMsg').textContent='';render()}
async function load(){const u=await client.auth.getUser(),user=u.data.user;if(!user){show('login',true);show('app',false);return}const p=await client.from('profiles').select('business_id,role').eq('id',user.id).single();if(p.error||!p.data){show('login',true);show('app',false);$('loginMsg').className='msg err';$('loginMsg').textContent='Your account is signed in, but it is not linked to Business Manager.';return}profile=p.data;show('login',false);show('app',true);$('userInfo').textContent='KelvoDigital · '+profile.role;await refresh()}