const SUPABASE_URL="https://fbgphoixzpykcpdbfbhd.supabase.co",SUPABASE_KEY="sb_publishable_U9E9amYU8RvRz4J1etv7Sw_svCjP-U-";
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on);
let profile=null,requests=[],projects=[],payments=[],documents=[],filter='all',pfilter='all',dfilter='all',selected=null,selectedProject=null,selectedDocument=null,projectRequestId=null;
const defaultAgreementTerms=`1. Scope of Work: Dareqo Digital will provide the selected service described in this agreement, offer sheet or invoice.
2. Delivery: Standard target is about 3 weeks after the required content and deposit are received.
3. Revisions: Up to 2 rounds of revisions are included unless otherwise agreed.
4. Payment: A 50% deposit is required to begin. The remaining balance is due before launch or handover.
5. Client Responsibilities: Client provides logo, photos, text, prices and required business information, reviews drafts and gives timely feedback.
6. Domain: After the first year, domain renewal is paid by the client.
7. Search/SEO: Search ranking or customer numbers cannot be guaranteed.
8. Approval: By accepting/signing, both parties confirm they understand and accept these terms.`;
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}
function pretty(s){return String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function phoneDigits(v){return String(v||'').replace(/\D/g,'')}
function paidForProject(id){return payments.filter(p=>p.project_id===id).reduce((a,p)=>a+Number(p.amount||0),0)}
function remainingForProject(p){return Math.max(0,Number(p.agreed_price||0)-paidForProject(p.id))}
function shareUrl(d){return location.origin+location.pathname.replace(/manager\.html.*$/,'document.html')+'?token='+encodeURIComponent(d.share_token)}
const pageMeta={
 dashboard:['Overview','See what needs attention and jump straight into the next task.'],
 requests:['Leads','Contact new customers, confirm work, and turn good leads into projects.'],
 add:['New Lead','Capture a new customer request with only the details you have.'],
 projects:['Projects','Keep jobs moving and update status, payments, expenses and documents.'],
 documents:['Documents','Create agreements, invoices and receipts only when needed.'],
 customers:['Customers','Your customer contact list, built automatically from leads.'],
 income:['Money','Track paid income, outstanding balances and profit.'],
 expenses:['Expenses','Record business and project costs.'],
 settings:['Settings','Business Manager defaults and document information.']
};
function setPage(name){
 document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));
 const page=$('page-'+name);if(!page)return;
 page.classList.remove('hidden');
 document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.page===name));
 const meta=pageMeta[name]||['Business Manager',''];$('pageTitle').textContent=meta[0];if($('pageHint'))$('pageHint').textContent=meta[1];
 window.scrollTo({top:0,behavior:'smooth'});render();
}
function requestTable(list){if(!list.length)return '<div class="empty">No leads here yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Customer</th><th>Type</th><th>Service</th><th>Status</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow requestrow" data-id="${x.id}"><td><b>${esc(x.customer_name)}</b><br><span class="muted">${esc(x.email||x.phone||'')}</span></td><td>${esc(pretty(x.request_type))}</td><td>${esc(x.service||'—')}</td><td><span class="pill">${esc(pretty(x.status))}</span></td></tr>`).join('')+'</tbody></table></div>'}
function projectTable(list){if(!list.length)return '<div class="empty">No projects yet. Confirm a lead or create a project to start.</div>';return '<div class="tablewrap"><table><thead><tr><th>Project</th><th>Customer</th><th>Status</th><th>Agreed</th><th>Paid</th><th>Balance</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow projectrow" data-id="${x.id}"><td><b>${esc(x.project_name)}</b><br><span class="muted">${esc(x.service||'')}</span></td><td>${esc(x.customer_name)}</td><td><span class="pill">${esc(pretty(x.status))}</span></td><td>${money(x.agreed_price)}</td><td class="good">${money(paidForProject(x.id))}</td><td>${money(remainingForProject(x))}</td></tr>`).join('')+'</tbody></table></div>'}
function documentTable(list){if(!list.length)return '<div class="empty">No documents yet. Create one only when you need to send something to a customer.</div>';return '<div class="tablewrap"><table><thead><tr><th>Type</th><th>Number</th><th>Client</th><th>Service</th><th>Status</th><th>Amount</th></tr></thead><tbody>'+list.map(x=>`<tr class="clickrow documentrow" data-id="${x.id}"><td><b>${esc(pretty(x.document_type))}</b></td><td>${esc(x.document_number||'—')}</td><td>${esc(x.customer_name||'—')}</td><td>${esc(x.service||x.title||'—')}</td><td><span class="pill docstatus">${esc(pretty(x.status))}</span></td><td>${money(x.amount)}</td></tr>`).join('')+'</tbody></table></div>'}
function paymentTable(){if(!payments.length)return '<div class="empty">No payments recorded yet.</div>';return '<div class="tablewrap"><table><thead><tr><th>Date</th><th>Project</th><th>Amount</th><th>Method</th><th>Note</th></tr></thead><tbody>'+payments.map(p=>{const pr=projects.find(x=>x.id===p.project_id);return `<tr><td>${esc(p.payment_date||'—')}</td><td>${esc(pr?.project_name||'Project')}</td><td class="good"><b>${money(p.amount)}</b></td><td>${esc(p.payment_method||'—')}</td><td>${esc(p.notes||'—')}</td></tr>`}).join('')+'</tbody></table></div>'}
function renderCustomers(){const map=new Map();requests.forEach(x=>{const key=(x.email||x.phone||x.customer_name||'').toLowerCase();if(!map.has(key))map.set(key,x)});const list=[...map.values()];$('customersList').innerHTML=list.length?'<div class="tablewrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Last service</th></tr></thead><tbody>'+list.map(x=>`<tr><td><b>${esc(x.customer_name)}</b></td><td>${esc(x.phone||'—')}</td><td>${esc(x.email||'—')}</td><td>${esc(x.service||'—')}</td></tr>`).join('')+'</tbody></table></div>':'<div class="empty">No customers yet. They will appear here after you add leads.</div>'}
function renderIncome(){const paid=payments.reduce((a,p)=>a+Number(p.amount||0),0),value=projects.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+Number(x.agreed_price||0),0),out=projects.filter(x=>x.status!=='cancelled').reduce((a,p)=>a+remainingForProject(p),0);$('incomeTotal').textContent=money(paid);$('outstandingTotal').textContent=money(out);$('projectValue').textContent=money(value);$('paymentsTable').innerHTML=paymentTable()}
function render(){if(!profile)return;const pending=requests.filter(x=>x.status==='pending').length,active=projects.filter(x=>!['completed','cancelled'].includes(x.status)).length,paid=payments.reduce((a,p)=>a+Number(p.amount||0),0),out=projects.filter(x=>x.status!=='cancelled').reduce((a,p)=>a+remainingForProject(p),0);$('pending').textContent=pending;$('activeProjects').textContent=active;$('income').textContent=money(paid);$('outstanding').textContent=money(out);$('dashboardProjects').innerHTML=projectTable(projects.filter(x=>!['completed','cancelled'].includes(x.status)).slice(0,6));$('dashboardDocuments').innerHTML=documentTable(documents.slice(0,6));let rl=requests;if(filter==='quote'||filter==='booking')rl=requests.filter(x=>x.request_type===filter);else if(filter!=='all')rl=requests.filter(x=>x.status===filter);$('requestsTable').innerHTML=requestTable(rl);let pl=pfilter==='all'?projects:projects.filter(x=>x.status===pfilter);$('projectsTable').innerHTML=projectTable(pl);let dl=dfilter==='all'?documents:documents.filter(x=>x.document_type===dfilter);$('documentsTable').innerHTML=documentTable(dl);bindRows();renderCustomers();renderIncome()}
function bindRows(){document.querySelectorAll('.requestrow').forEach(r=>r.onclick=()=>openDetail(r.dataset.id));document.querySelectorAll('.projectrow').forEach(r=>r.onclick=()=>openProject(r.dataset.id));document.querySelectorAll('.documentrow').forEach(r=>r.onclick=()=>openDocument(r.dataset.id))}
async function refresh(){const [rq,pq,pyq,dq]=await Promise.all([client.from('requests').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false}),client.from('projects').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false}),client.from('payments').select('*').eq('business_id',profile.business_id).order('payment_date',{ascending:false}).order('created_at',{ascending:false}),client.from('documents').select('*').eq('business_id',profile.business_id).order('created_at',{ascending:false})]);for(const q of [rq,pq,pyq,dq])if(q.error){$('globalMsg').className='msg err';$('globalMsg').textContent=q.error.message;return}requests=rq.data||[];projects=pq.data||[];payments=pyq.data||[];documents=dq.data||[];$('globalMsg').textContent='';render()}
async function load(){const u=await client.auth.getUser(),user=u.data.user;if(!user){show('login',true);show('app',false);return}const p=await client.from('profiles').select('business_id,role').eq('id',user.id).single();if(p.error||!p.data){show('login',true);show('app',false);$('loginMsg').className='msg err';$('loginMsg').textContent='Your account is signed in, but it is not linked to Business Manager.';return}profile=p.data;show('login',false);show('app',true);$('userInfo').textContent='Dareqo Digital · '+pretty(profile.role);await refresh()}